# Generated by Django 2.2.6 on 2019-10-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120, verbose_name='Item_name')),
                ('item_id', models.IntegerField(blank=True, default=1, null=True)),
                ('img_name', models.CharField(max_length=120, verbose_name='Image_name')),
                ('price', models.IntegerField(blank=True, default=1, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('brand_name', models.CharField(max_length=120, verbose_name='brand_name')),
                ('class_name', models.CharField(max_length=120, verbose_name='class_name')),
            ],
        ),
    ]
