# Generated by Django 2.2.6 on 2019-10-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120, verbose_name='Username')),
                ('mobileno', models.CharField(max_length=120, verbose_name='Mobile no')),
                ('state', models.CharField(max_length=120, verbose_name='State')),
            ],
        ),
    ]
