# Generated by Django 2.2.6 on 2019-10-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
