# Generated by Django 2.2.6 on 2019-10-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120, verbose_name='Username')),
                ('item_id', models.IntegerField(blank=True, default=1, null=True)),
                ('user_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.IntegerField(blank=True, default=1, null=True)),
                ('address', models.CharField(max_length=120, verbose_name='Address')),
                ('mobileno', models.CharField(max_length=120, verbose_name='Mobile no')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('transaction_id', models.CharField(max_length=120, verbose_name='Transacton_id')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(blank=True, default=1, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
